### ISSUE TITLE
Define a release condition

### ISSUE THREAD

**Issue by mikegogulski** [conreality/conreality#18]
Ex:

0.1.0 Yay!
0.1.1 whatever
0.1.2 whatever
0.2.0 YAY!
0.2.1 bugfixes!

etc.

Ideally, this should be programmatic, e.g. "when all tests pass, and new capability introduced, minor_version++"

**Comment by mikegogulski** [comment]
or, I suppose, adopt someone else's standard.

**Comment by bendiken** [comment]
We would go ahead and adhere to [semantic versioning](http://semver.org/), same as everyone else. But there's no need to cut releases until we're building binaries for Debian etc, and have actual users.

**Comment by ab0032** [comment]
If we give releases a name, I think it is good to keep them in alphabetical
order, so you always can tell which is earlier and which the latest just
from the name.
Semantic versioning is great, but it is good to be able to tell
experimental from stable releases by there numbers, perhaps use odd and
even numbers?

**Comment by bendiken** [comment]
@ab0032 The standard practice is to suffix development releases with `-dev`, `-alpha`, `-beta`, etc. The odd/even version number practice has been abandoned by pretty much everyone, including the Linux kernel, as it is rather confusing to users.

**Comment by mikegogulski** [comment]
OK, agreed on semantic versioning.

I kinda like the idea of having minor releases get names also, a la Ubuntu with "Wily Werewolf" and so on. Some time when I'm not sleepy I'll try to think up some candidate classes to use instead of animals. Science fiction writers comes to mind, but there's another project I've seen recently that's using those already.

**Comment by bendiken** [comment]
We are about to get going with formal releases starting with 0.0.1 imminently (https://github.com/conreality/conreality/issues/21). I'll create milestones for subsequent near-term releases once that one is out the door.

@mikegogulski Still could use thinking on release nicknaming, but that's not urgent as we wouldn't do it for point releases, only major releases.
