### ISSUE TITLE
Ensure benchmarks can be compiled on ARM

### ISSUE THREAD

**Issue by mikegogulski** [conreality/conreality#19]
Jane Street's Core_bench module uses an x86 assembler instruction to access a cycles-since-reset counter. ARMv6+ processors have a similar counter, but their module doesn't support it (yet).

For now, I'l just going to dodge this via some hackery in the Makefile.

I've opened a ticket with Jane Street here: https://github.com/janestreet/core_bench/issues/9

**Comment by mikegogulski** [comment]
Dodged via d0fc3c37bc9dff302316c4635f43a7f9c19b7277

Hold this open pending a fix to Core_bench

**Comment by bendiken** [comment]
Overcome by events.
