### ISSUE TITLE
geometry needs attention

### ISSUE THREAD

**Issue by mikegogulski** [conreality/conreality#20]
I'm fatigued by looking at this module, mostly because my math isn't up to snuff.

Also, someone else needs to look at it anyway, to ensure that the tests cover edge cases I haven't thought of.

Finally, there would be same value in extending the benchmark suite to cover alternative implementations of the various functions -- especially given that compiler optimizations may be very different across the architectures we are targeting.

Right now, functions that aren't working are made to pass tests with the todo() function. There are a couple that are essential, I think, like slerp() and nlerp() for quaternions.

**Comment by ab0032** [comment]
I can do that, but not this year.
a

**Comment by mikegogulski** [comment]
Super!

**Comment by bendiken** [comment]
Overcome by events.
